repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.3.0'
  hooks:
  - id: check-yaml
    exclude: ^\.deploy/helm/app/templates/.*\.(yml|yaml)
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: local
  hooks:
    - id: ruff check
      name: ruff check
      entry: ruff check --fix
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      pass_filenames: false
      types: [python]
    - id: ruff format
      name: ruff format
      entry: ruff format
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      pass_filenames: false
      types: [python]
    - id: pyright
      name: pyright
      entry: python -m pyright
      language: system  # the language of the hook - tells pre-commit how to install the hook.
      pass_filenames: false
      types: [python]
