---

app:
  env:
    API_ROOT_PATH: "/{{cookiecutter.__project_kebab}}"

    LOG_FORMATTER: "json"
    # Warning: Sentry DSN is unique for each project.
    # Do not copy-paste this value from other projects
    SENTRY_DSN: ""
    SENTRY_CLUSTER: "prod"

  secretEnv:
    DB_URL: ref+vault://gitlab/${CI_PROJECT_PATH}/${CI_ENVIRONMENT_NAME}#/DB_URL

ingress:
  enabled: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Access-Control-Allow-Origin: http://localhost:8080";
      more_set_headers "Access-Control-Allow-Methods: GET, PUT, POST, DELETE, PATCH, OPTIONS";
      more_set_headers "Access-Control-Allow-Headers: *";
      more_set_headers "Access-Control-Allow-Credentials: true";
  ingressClassName: nginx-new-internal
  hosts:
    # The same must be specified in .gitlab-ci.yml as dev url
    - host: svc.prod.internal.distribusion.com
      paths:
        - path: "/{{cookiecutter.__project_kebab}}(/|$)(.*)"
          type: Prefix

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 8m
    memory: 128Mi

metrics:
  serviceMonitor:
    enabled: true

persistentVolume:
  enabled: false
